// Structural checks on the blog data the site actually imports.
//
// src/data/blogPosts.json is generated by `npm run build:blog`, but it is also
// the committed source the Astro routes read, so its shape is asserted here
// rather than only in the built-output checks.
import { describe, expect, it } from 'vitest';
import posts from '../src/data/blogPosts.json' with { type: 'json' };
import { pageSize, archives, categoryFor, postsWithCategory } from '../src/data/blog.ts';

const REQUIRED_FIELDS = ['slug', 'title', 'date', 'author', 'image', 'imageAlt', 'excerpt', 'content'];

describe('blogPosts.json', () => {
  it('carries every field the article template renders', () => {
    for (const post of posts) {
      for (const field of REQUIRED_FIELDS) {
        expect(post, `${post.slug} is missing "${field}"`).toHaveProperty(field);
        expect(typeof post[field], `${post.slug}.${field} must be a string`).toBe('string');
      }
    }
  });

  it('has a unique slug for every article', () => {
    const slugs = posts.map((post) => post.slug);
    expect(new Set(slugs).size).toBe(slugs.length);
  });

  it('uses route-safe slugs that Astro can map to a directory', () => {
    for (const post of posts) {
      expect(post.slug, `${post.slug} must be lowercase, hyphenated and URL-safe`).toMatch(/^[a-z0-9]+(?:-[a-z0-9]+)*$/);
      expect(post.slug).toBe(post.slug.toLowerCase());
      expect(post.slug).not.toMatch(/^-|-$/);
    }
  });

  it('stores an ISO date and derives its label in one place', async () => {
    const { formatPostDate } = await import('../src/data/dates.ts');
    for (const post of posts) {
      expect(post.date, `${post.slug} date must be YYYY-MM-DD`).toMatch(/^\d{4}-\d{2}-\d{2}$/);
      expect(Number.isNaN(Date.parse(post.date)), `${post.slug} date must be a real date`).toBe(false);
      expect(post, `${post.slug} must not store a duplicate dateLabel`).not.toHaveProperty('dateLabel');
      expect(formatPostDate(post.date), `${post.slug} label must describe its date`).toMatch(/^[A-Z][a-z]+ \d{1,2}, \d{4}$/);
    }
  });

  it('keeps every article long enough for the length floor', () => {
    for (const post of posts) {
      expect(post.content.length, `${post.slug} must exceed 1000 characters`).toBeGreaterThan(1000);
      expect(post.excerpt.length, `${post.slug} excerpt must be a usable meta description`).toBeGreaterThan(40);
    }
  });

  it('describes every article image', () => {
    for (const post of posts) {
      expect(post.image, `${post.slug} image must be an absolute path`).toMatch(/^\//);
      expect(post.imageAlt.trim().length, `${post.slug} needs imageAlt text`).toBeGreaterThan(0);
    }
  });

  it('does not ship unresolved template placeholders', () => {
    for (const post of posts) {
      expect(post.content, `${post.slug} still has a {{placeholder}}`).not.toMatch(/\{\{|\}\}/);
    }
  });

  it('files every article under a declared category', () => {
    expect(postsWithCategory).toHaveLength(posts.length);
    for (const archive of archives) {
      expect(archive.items.length, `archive ${archive.slug} paginates from the same list`).toBe(archive.total);
      expect(archive.pageCount).toBe(Math.max(1, Math.ceil(archive.total / pageSize)));
    }
    for (const post of posts) {
      expect(['local-guides', 'storage-options', 'storage-tips']).toContain(categoryFor(post.slug));
    }
  });
});
