import fs from 'node:fs';
const hub = fs.readFileSync('dist/storage-near-you/index.html', 'utf8');
const count = (re) => (hub.match(re) || []).length;
console.log('len', hub.length);
console.log('location-list (areas)', count(/class="location-list"/g));
console.log('location-area', count(/class="location-area"/g));
console.log('location-item (non-link)', count(/class="location-item"/g));
console.log('suburb guide links', count(/href="\/(?:west-auckland-storage|discovering-west-auckland)/g));
console.log('hub in sitemap.xml', fs.readFileSync('dist/sitemap.xml', 'utf8').includes('/storage-near-you/'));
console.log('footer link present on article', fs.readFileSync('dist/boat-storage-at-west-auckland-storage/index.html', 'utf8').includes('/storage-near-you/'));
